require("the-real-night.plugins.code-execution-and-debugging.toggleTerm")
require("the-real-night.plugins.code-execution-and-debugging.dapui")
--require("the-real-night.plugins.code-execution-and-debugging.dap-view")
require("the-real-night.plugins.code-execution-and-debugging.dap")
require("the-real-night.plugins.code-execution-and-debugging.dap-virtual-text")
